import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const circularFont = localFont({
  src: "../public/fonts/circularweb-book.woff2",
  variable: "--font-circular",
});

const generalFont = localFont({
  src: "../public/fonts/general.woff2",
  variable: "--font-general",
});

const robertRegular = localFont({
  src: "../public/fonts/robert-regular.woff2",
  variable: "--font-robert-regular",
});

const robertMedium = localFont({
  src: "../public/fonts/robert-medium.woff2",
  variable: "--font-robert-medium",
});

const zentryFont = localFont({
  src: "../public/fonts/zentry-regular.woff2",
  variable: "--font-zentry",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${circularFont.variable} ${generalFont.variable} ${robertRegular.variable} ${robertMedium.variable} ${zentryFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
